# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GateToPayOnboardingSDK'
  pod 'Alamofire'
  pod 'GoogleMLKit/FaceDetection'
  pod 'lottie-ios', '~> 3.3.0'
  #pod 'netfox'
  pod 'NVActivityIndicatorView', '~> 4.8.0'
  pod 'IQKeyboardManagerSwift'
  pod 'OTPFieldView'
  pod 'FADesignable'
  pod 'DropDown'
  pod 'SwiftMessages', '~> 9.0.6'
  pod 'AMPopTip'
  pod 'DatePickerDialog'
  pod 'UDatePicker', :git=>  "https://github.com/zaidiabbas/UDatePicker"
  pod 'FAPickerView'                        # Picker vi
  pod 'Protobuf', '~> 3.25'

  # Pods for Example

end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

    end
  end
end
